"""add_iban_to_account

Revision ID: 00fb2329081b
Revises: 6dd3599119b6
Create Date: 2026-01-31 19:06:46.481187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fb2329081b'
down_revision: Union[str, Sequence[str], None] = '6dd3599119b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('iban', sa.String(length=34), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'iban')
    # ### end Alembic commands ###
