"""add_timestamp_to_transactions

Revision ID: 6dd3599119b6
Revises: 7e06b3f6ef19
Create Date: 2026-01-31 19:04:04.323086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd3599119b6'
down_revision: Union[str, Sequence[str], None] = '7e06b3f6ef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'timestamp')
    # ### end Alembic commands ###
