"""add_user_roles_and_is_active_default

Revision ID: 7e06b3f6ef19
Revises: ea55eeea9c54
Create Date: 2026-01-31 11:50:51.171169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e06b3f6ef19'
down_revision: Union[str, Sequence[str], None] = 'ea55eeea9c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
    op.alter_column('users', 'is_active', server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
