"""update_transaction_model_with_type_and_transfer

Revision ID: ea55eeea9c54
Revises: 3c4d5e6f7a8b
Create Date: 2026-01-31 10:01:57.044390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea55eeea9c54'
down_revision: Union[str, Sequence[str], None] = '3c4d5e6f7a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('target_account_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('type', sa.String(length=50), nullable=False, server_default='Expense'))
    op.create_foreign_key(None, 'transactions', 'accounts', ['target_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'target_account_id')
    # ### end Alembic commands ###
